### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ghost** [notpushkin/mkdocs-alabaster#10]
@iamale I reviewed and merged #7, and made 2 fixes, we're ready for a new pypi release. Thanks.

**Comment by notpushkin** [comment]
Published as [0.7.4](https://pypi.python.org/pypi/mkdocs-alabaster/0.7.4)! Thank you and @moigagoo for your great work.

**Comment by moigagoo** [comment]
Thank _you_ guys for the great theme!

**Comment by ghost** [comment]
[I can't take much credit :wink: this is all @iamale ](https://github.com/iamale/mkdocs-alabaster/graphs/contributors)

**Comment by notpushkin** [comment]
Well, I can't take much credit too then — it's all @bitprophet, @kennethreitz and @mitsuhiko, actually. :^)

**Comment by kennethreitz** [comment]
@iamale Oxford comma!
