### ISSUE TITLE
link to github repo on example page

### ISSUE THREAD

**Issue by kennethreitz** [notpushkin/mkdocs-alabaster#12]
here: http://mkdocs-alabaster.ale.rocks

**Comment by notpushkin** [comment]
I think it'll finally motivate me to work on #1 :^)

**Comment by ghost** [comment]
I was just writing a comment to say: isn't this a nav issue? so we're thinking the same thing.

there is the following in config, but not showing on sidebar.

```
  extra_nav_links:
    Fork me on GitHub: https://github.com/iamale/mkdocs-alabaster
```

**Comment by moigagoo** [comment]
The link is there: http://take.ms/jIb37

Closing the issue.
