### ISSUE TITLE
Missing Configuration File

### ISSUE THREAD

**Issue by rohanpurekar** [notpushkin/mkdocs-alabaster#18]
Error - Config Value : The theme 'alabaster' does not appear to have a configuration file. Please upgrade to a current version of the theme

Getting this error when selecting alabaster as the theme

**Comment by notpushkin** [comment]
Hi Rohan! Sorry, version 0.7.5 wasn't published on PyPI for some reason – I've just uploaded it, could you please upgrade and try it?

**Comment by rohanpurekar** [comment]
Thanks man!

**Comment by mandel01** [comment]
Hi, thanks for this great port of the alabaster theme! I just installed mkdocs & mkdocs-alabaster (0.7.5) for the first time today, and I ran into this same error. Is it working for you @rap999a ?


```
$ mkdocs serve
INFO    -  Building documentation... 
ERROR   -  Config value: 'theme'. Error: The theme 'alabaster' does not appear to have a configuration file. Please upgrade to a current version of the theme. 

Aborted with 1 Configuration Errors!
```


```
mkdocs           1.0.4     
mkdocs-alabaster 0.7.5
```

**Comment by mstuttgart** [comment]
I find this same error here. I installed the laste version of code, using github:

```
pip install git+https://github.com/notpushkin/mkdocs-alabaster.git
```

Run mkdocs serve:

```
]INFO    -  Building documentation... 
ERROR   -  Config value: 'theme'. Error: The theme 'alabaster' does not appear to have a configuration file. Please upgrade to a current version of the theme. 

Aborted with 1 Configuration Errors!
```
@mandel01 , @rap999a , @notpushkin do you find any solution?

**Comment by mandel01** [comment]
Unfortunately no. I switched to the [cinder](https://sourcefoundry.org/cinder/) theme for now.

**Comment by tknv** [comment]
Hi @mstuttgart @mandel01 @rap999a , put a `mkdocs_theme.yml` file in `xxx/site-packages/mkdocs_alabaster/` 
xxx will be your using python env.  
`mkdocs_theme.yml` contain...
```yaml
# Hi
```
I am not familiar to custom mkdocs, but maybe that is for config code highlight etc etc.....

**Comment by notpushkin** [comment]
Hey guys, sorry for the decades of silence from me :( I guess I've figured out the problem: I need to add *.yml to MANIFEST.IN and republish the package on PyPI so that the mkdocs_theme.yml gets actually installed. I'll try to do it ASAP, probably later today if my laptop doesn't run out; thank you for your patience!
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by notpushkin** [comment]
@mstuttgart @mandel01 @rap999a @tknv: can you please try the new 0.7.6 version? It is on PyPI already.

**Comment by karlssonjohan** [comment]
Hi,
it does not work. It "works" if I copy the file alabaster_theme.yml to mkdocs_theme.yml. 

```
mkdocs build --verbose --clean --theme alabaster
DEBUG   -  Loading configuration file: /home/user/work/mk3/mkdocs.yml 
DEBUG   -  [Errno 2] No such file or directory: '/home/user/.local/lib/python3.6/site-packages/mkdocs_alabaster/mkdocs_theme.yml' 
ERROR   -  Config value: 'theme'. Error: The theme 'alabaster' does not appear to have a configuration file. Please upgrade to a current version of the theme. 
```

**Comment by steven-esser** [comment]
Opened a PR #19 that simply renames the `alabaster_theme.yml` to `mkdocs_theme.yml`. 

This will fix the issues everyone is having in this ticket. You will have to install via git until @notpushkin merges and pushes a new release to PyPi.

**Comment by notpushkin** [comment]
0.7.7 is on PyPI, thanks @majurg!
