### ISSUE TITLE
Links to previous and next duplicate paths in related.html

### ISSUE THREAD

**Issue by nevenjovanovic** [notpushkin/mkdocs-alabaster#21]
In mkdocs_alabaster/sidebars/related.html , line 5, the expression `{{page.previous_page.url}}` produces incorrect relative URLs of the type `docs/page/docs/previouspage`, where just `docs/previouspage` is expected.
I use mkdocs version 1.0.4 with Python 3.5.
I solved this by replacing the expression `{{page.previous_page.url}}` in line 5 with `{{ page.previous_page.url | url }}`, as found on https://github.com/squidfunk/mkdocs-material/blob/master/src/partials/footer.html line 35.

**Comment by moigagoo** [comment]
@nevenjovanovic Hi! Thanks for reporting the issue. Would you mind submitting a PR with the fix?
