### ISSUE TITLE
pypi version update request

### ISSUE THREAD

**Issue by ghost** [notpushkin/mkdocs-alabaster#5]
Please update pypi with the new 404 template! Many thanks.

**Comment by notpushkin** [comment]
I'm on it!

**Comment by ghost** [comment]
How's the progress on this? I'm still seeing 0.7.1 on pypi.

**Comment by notpushkin** [comment]
I'm having trouble accessing my old PyPI account, sorry! Once I recover it, I'll publish the new version

**Comment by ghost** [comment]
ah no problem. thanks for the update.

**Comment by ghost** [comment]
Just checking on the progress on this. Sorry if I'm being annoying but I'd love to use the new 404 template! Thanks!

**Comment by notpushkin** [comment]
Later this evening!

**Comment by notpushkin** [comment]
0.7.3 on PyPI now, please check

**Comment by ghost** [comment]
Perfect! Works well, and builds the 404 page nicely. Many thanks! :clap:

**Comment by notpushkin** [comment]
Yeah! Sorry for the huge delay.
By the way, any chance you could help me maintain this project? I'm not a really active MkDocs user lately. :(

**Comment by ghost** [comment]
Sure, did you want to add me onto this repo? or add me on pypi as well? either is fine. and I'll help out however I can.
